
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightASIGNARrightVARIABLESrightMAYORrightIGUALrightRESTArightFORMULASrightSTRINGrightESTRUCTURAASIGNAR ESTRUCTURA FORMULAS IGUAL MAYOR RESTA STRING VARIABLESdeclaracion : ASIGNARdeclaracion : VARIABLESdeclaracion : MAYORdeclaracion : IGUALdeclaracion : RESTAdeclaracion : FORMULASdeclaracion : STRINGdeclaracion : ESTRUCTURA'
    
_lr_action_items = {'ASIGNAR':([0,],[2,]),'VARIABLES':([0,],[3,]),'MAYOR':([0,],[4,]),'IGUAL':([0,],[5,]),'RESTA':([0,],[6,]),'FORMULAS':([0,],[7,]),'STRING':([0,],[8,]),'ESTRUCTURA':([0,],[9,]),'$end':([1,2,3,4,5,6,7,8,9,],[0,-1,-2,-3,-4,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaracion':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaracion","S'",1,None,None,None),
  ('declaracion -> ASIGNAR','declaracion',1,'p_declaracion_asignacion','AnalizadorSintactico.py',22),
  ('declaracion -> VARIABLES','declaracion',1,'p_declaracion_variables','AnalizadorSintactico.py',26),
  ('declaracion -> MAYOR','declaracion',1,'p_declaracion_mayor','AnalizadorSintactico.py',30),
  ('declaracion -> IGUAL','declaracion',1,'p_declaracion_igual','AnalizadorSintactico.py',34),
  ('declaracion -> RESTA','declaracion',1,'p_declaracion_resta','AnalizadorSintactico.py',38),
  ('declaracion -> FORMULAS','declaracion',1,'p_declaracion_formulas','AnalizadorSintactico.py',42),
  ('declaracion -> STRING','declaracion',1,'p_declaracion_string','AnalizadorSintactico.py',46),
  ('declaracion -> ESTRUCTURA','declaracion',1,'p_declaracion_estructura','AnalizadorSintactico.py',50),
]
